version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: web-tracing-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_tracing
      MYSQL_USER: tracing
      MYSQL_PASSWORD: tracing
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - web-tracing-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 后端服务
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: web-tracing-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./backend/config:/root/config
    ports:
      - "8080:8080"
    networks:
      - web-tracing-network

  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: web-tracing-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - web-tracing-network

networks:
  web-tracing-network:
    driver: bridge

volumes:
  mysql-data:
