# .air.toml 配置文件

# 工作目录
# 使用 . 或绝对路径，请注意 `tmp_dir` 目录必须在 `root` 目录下
root = "."
tmp_dir = "tmp"

[build]
# 只需要监听 Go 文件的变化
include_ext = ["go"]
# 忽略这些文件扩展名或目录
exclude_dir = ["tmp", "vendor", "docs"]
# 监听以下指定目录的文件
include_dir = []
# 排除以下文件
exclude_file = []
# 如果文件更改过于频繁，则没有必要在每次更改时都触发构建
delay = 1000 # ms
# 发生构建错误时，停止运行旧的二进制文件
stop_on_error = true
# air 的日志文件名，该日志文件放置在你的 `tmp_dir` 中
log = "air_errors.log"
# 指定主文件
main = "cmd/main.go"
# 构建命令
cmd = "go build -o ./tmp/main ./cmd/main.go"
# 运行命令
bin = "./tmp/main"

[log]
# 显示日志时间
time = true

[color]
# 自定义每个部分显示的颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 退出时删除 tmp 目录
clean_on_exit = true
